### ISSUE TITLE
I have some questions about the principle of this paper

### ISSUE THREAD

**Issue by Old-Young233** [jungokasai/beam_with_patience#1]
I still don't understand your method after reading the paper, it says "_stopping criteria that yield accurate search improve performance_" when setting `patience factor=2`, can't it be interpreted as making beam search search the candidate translation of `beam_size*2`

But I tested the case of `beam_size=10` and `beam_size=5, patience factor=2`, and found that the BLEU value of the latter is higher, is my understanding of the principle of the algorithm biased, I hope to get your answer.

**Comment by jungokasai** [comment]
Thank you for your question. `beam_size` and `beam_size*patiance_factor` are different. The former controls the **breadth** and the latter the **depth** of search. And the latter is only used in the stopping criterion (because it's depth!): https://github.com/jungokasai/beam_with_patience/blob/main/fairseq/fairseq/sequence_generator.py#L712. 
Now, the original implementation of [fairseq](https://github.com/pytorch/fairseq/blob/main/fairseq/sequence_generator.py#L711) (and Hugging Face as well) **ties** these two different numbers. But there's no reason to do so, and it is rather an odd heuristic as we discussed in the paper. 

The patience factor changes the depth while **keeping the same breadth**. So indeed, what you got is expected. Now why does a larger search breadth hurt performance (despite its more "accurate" search)? It is known as the "beam search curse"; e.g., https://arxiv.org/abs/1808.09582. Higher scores under a locally normalized models do not always translate to better generation quality.
